name: Release on NPM

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Validate code and tests
        run: |
          yarn lint
          yarn test

      - name: Build library
        run: npx rollup -c

      # Publish version to public repository
      - name: Publish
        run: yarn publish --verbose --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
