name: Release on NPM

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Validate code and tests
        run: |
          npm run lint
          npm test

      - name: Build library
        run: npx rollup -c

      - name: Increment version and publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm login --registry https://registry.npmjs.org/
          npm publish
